apiVersion: v2
appVersion: v3.4.0
version: 3.4.0
dependencies:
  - name: kubernetes-secrets-generator
    version: 3.4.0
    repository: https://helm.mittwald.de
    condition: ""
    alias: kubernetes-secrets-generator
    tags: []
    import-values: []
deprecated: false
description: Controller for automatically creating random secret values
keywords:
  - controller
kubeVersion: ">=1.24.0-0"
name: kubernetes-secrets-generator
sources:
  - https://github.com/mittwald/kubernetes-secret-generator
type: application