traefik:
  deployment:
    replicas: 3
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 1
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true
    kubernetesIngress:
      enabled: false
  globalArguments: []
  ports:
    traefik:
      port: 9000
      exposedPort: 9000
      expose: false
      exposeInternal: true
      protocol: TCP
    metrics:
      port: 9100
      exposedPort: 9100
      expose: false
      exposeInternal: true
      protocol: TCP
    web:
      port: 80
      exposedPort: 80
      expose: true
      exposeInternal: false
      protocol: TCP
      redirectTo:
        port: websecure
        priority: 1
    websecure:
      port: 443
      exposedPort: 443
      expose: true
      exposeInternal: false
      protocol: TCP
  service:
    enabled: true
    type: LoadBalancer