type: deployment
replicaCount: 1
terminationGracePeriodSeconds: 10

securityContext:
  user: 556   

database:
  postgresql:
    enabled: true

apiKey: false

image:
  registry: "docker.io"
  repository: "fallenbagel/jellyseerr"
  tag: "preview-postgres@sha256:15f9bd26ec3d3e6aa9b0459604a39797e0003dbb5cf7c22b2df835c3aea2c503"

service:
  enabled: true
  headless: false
  publishNotReadyAddresses: true
  loadbalancer:
    - name: jellyseerr
      protocol: TCP
      port: 5055

storage:
  enabled: true
  volumes:
    - name: "config"
      type: "pvc"
      mountPath: "/app/config"
      accessModes:
      - ReadWriteOnce
      # - ReadWriteMany # Can't use with local-path
      storageClass: "local-path"
      size: 1Gi
      readOnly: false