type: deployment
image:
  registry: "docker.io"
  repository: "traefik"
  tag: "v2.10.7"

containerArgs:
  - --global.checknewversion=false
  - --global.sendanonymoususage=false
  - --accesslog.format=common
  - --log.format=common
  - --log.level=info
  - --api.dashboard=false
  - --ping
  - --providers.kubernetescrd
  - --providers.kubernetescrd.allowcrossnamespace=true
  - --entryPoints.traefik.address=:8080/tcp
  - --entryPoints.web.address=:80/tcp
  - --entryPoints.websecure.address=:443/tcp
  - --entrypoints.web.http.redirections.entryPoint.to=websecure

traefik:
  certificateIssuer:
    enabled: true
    name: "letsencrypt-production"
    email: "contact@projectwhitebox.com"
    solvers:
      dns:
        enabled: true
        provider: cloudflare # cloudflare | njalla
        email: "contact@projectwhitebox.com"
        dnsZones:
          - "*.projectwhitebox.com"

probes:
  readiness:
    enabled: true
    type: "http"
    httpPath: "/ping"
    httpPort: 8080
    initialDelaySeconds: 2
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 1
  liveness:
    enabled: true
    type: "http"
    httpPath: "/ping"
    httpPort: 8080
    initialDelaySeconds: 2
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3
  startup:
    enabled: true
    type: "http"
    httpPath: "/ping"
    httpPort: 8080
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3

service:
  enabled: true
  headless: false
  clusterip:
    - name: dashboard
      protocol: TCP
      port: 8080
  loadbalancer:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443

rbac:
  enabled: true
  type: clusterrole
  rules:
    - apiGroups:
        - ""
      resources:
        - services
        - endpoints
        - secrets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
        - networking.k8s.io
      resources:
        - ingresses
        - ingressclasses
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
        - networking.k8s.io
      resources:
        - ingresses/status
      verbs:
        - update
    - apiGroups:
        - traefik.io
        - traefik.containo.us
      resources:
        - middlewares
        - middlewaretcps
        - ingressroutes
        - traefikservices
        - ingressroutetcps
        - ingressrouteudps
        - tlsoptions
        - tlsstores
        - serverstransports
      verbs:
        - get
        - list
        - watch

ingress:
  traefik:
    enabled: true
    hosts:
    - name: https
      entrypoint: "websecure"
      host: "traefik.projectwhitebox.com"
      backendPort: 8080
      securityHeaders: true
      cors:
        enabled: false
        accessControlAllowMethods: []
        accessControlAllowHeaders: []
        accessControlAllowOriginList: []
        accessControlMaxAge: null
        addVaryHeader: null
      tls: true