image:
  registry: "docker.io"
  repository: "traefik"
  tag: "v2.10"

containerArgs:
  - --api.insecure
  - --providers.kubernetesingress

service:
  enabled: true
  clusterip:
    - name: dashboard
      protocol: TCP
      port: 8080
  nodeport:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      nodePort: 30443

ingress:
  traefik:
    enabled: true
    hosts:
    - name: https
      entrypoint: "websecure"
      host: "example.com"
      backendPort: 443
      middlewares:
      - "basic"
      - "test"
      certManager:
        enabled: true
        issuer: "test/example" # namespace/issuerName or just issuerName for cluster issuer
    - name: http
      entrypoint: "web"
      host: "example.com"
      backendPort: 80
      middlewares:
      - "basic"
      - "http"
      certManager:
        enabled: false
        issuer: "" # namespace/issuerName or just issuerName for cluster issuer

serviceAccount:
  enabled: true

rbac:
  enabled: true
  type: clusterrole
  rules:
    - apiGroups:
        - ""
      resources:
        - services
        - endpoints
        - secrets
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
        - networking.k8s.io
      resources:
        - ingresses
        - ingressclasses
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - extensions
        - networking.k8s.io
      resources:
        - ingresses/status
      verbs:
        - update