istio-ingressgateway:
  service:
    type: LoadBalancer
    ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP

traefik:
  accessLogFormat: "common"
  logFormat: "common"
  logLevel: "info"
  entrypoints:
    - name: traefik
      port: 8080
      protocol: TCP
    - name: web
      port: 80
      protocol: TCP
      redirectToEntrypoint: "websecure"
    - name: websecure
      port: 443
      protocol: TCP
  certificateIssuer:
    enabled: true
    name: "letsencrypt-production"
    email: "contact@projectwhitebox.com"
    solvers:
      dns:
        enabled: true
        provider: cloudflare # cloudflare | njalla
        email: "contact@projectwhitebox.com"
        dnsZones:
          - "*.projectwhitebox.com"