{{- if eq .Values.apiKey true }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-api-credentials
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: key
data: {}
{{- end }}