{{- if .Values.certificateIssuer.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: letsencrypt-production
spec:
  secretName: certificate-secret
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: {{ .Values.certificateIssuer.certificates }}
{{- end }}