{{- if .Values.certificateIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certificateIssuer.contactEmail }}
    privateKeySecretRef:
      name:  letsencrypt-prod-key
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.certificateIssuer.cloudflareEmail }}
            apiTokenSecretRef:
              name: cloudflare-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "{{ index .Values.certificateIssuer.dnzZones 0 }}"
{{- end }}