{{- if and (.Values.certificateIssuer.enabled) (eq .Release.Name "traefik") }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certificateIssuer.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certificateIssuer.email }}
    privateKeySecretRef:
      name:  {{ .Values.certificateIssuer.name }}-key
    solvers:
      {{- if .Values.certificateIssuer.solvers.dns.cloudflare.enabled }}
      - dns01:
          cloudflare:
            email: {{ .Values.certificateIssuer.solvers.dns.cloudflare.email }}
            apiTokenSecretRef:
              name: cloudflare-secret
              key: cloudflare-token
        selector:
          dnsZones:
        {{- range .Values.certificateIssuer.solvers.dns.cloudflare.dnsZones }}
            - "{{ . }}"
        {{- end }}
      {{- end }}
{{- end }}