apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
              gpu: {{ .Values.resources.limits.gpu }}
          {{- end }}
          {{- if or .Values.containerArgs (eq .Release.Name "traefik") }}
          env:
          {{- if and .Values.traefik.certificateIssuer.solvers.dns.enabled (eq .Release.Name "traefik") }}
          - name: {{ upper .Values.traefik.certificateIssuer.solvers.dns.provider }}_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.traefik.certificateIssuer.solvers.dns.provider }}-secret
                key: {{ .Values.traefik.certificateIssuer.solvers.dns.provider }}-token
          - name: LEGO_DISABLE_CNAME_SUPPORT
            value: "true"
          {{- end }}
          {{- end }}
          {{- if or .Values.containerArgs (eq .Release.Name "traefik") }}
          args:
            {{- if .Values.containerArgs }}
            # Container Args
            {{- toYaml .Values.containerArgs | nindent 12 }}
            {{- end }}

            - --certificatesresolvers.myresolver.acme.email=contact@projectwhitebox.com
            - --certificatesresolvers.myresolver.acme.storage=acme.json
            - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
            - --certificatesresolvers.myresolver.acme.certificatesDuration=2160
            - --certificatesresolvers.myresolver.acme.dnschallenge=true
            - --certificatesresolvers.myresolver.acme.dnschallenge.provider=njalla
            - --certificatesresolvers.myresolver.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53







            # {{- if eq .Release.Name "traefik" }}
            # # Traefik
            # - --accesslog.format={{ .Values.traefik.accessLogFormat }}
            # - --log.format={{ .Values.traefik.logFormat }}
            # - --log.level={{ .Values.traefik.logLevel }}
            # - --api.insecure
            # - --providers.kubernetesingress
            # - --entrypoints.web.http.redirections.entryPoint.to=websecure
            # - --entrypoints.web.http.redirections.entryPoint.scheme=https
            # - --entrypoints.websecure.http.tls=true
            # - --entrypoints.websecure.http.tls.certresolver=letsencrypt
            # - --entrypoints.websecure.http.tls.domains[0].main=projectwhitebox.com
            # - --entrypoints.websecure.http.tls.domains[0].sans=*.projectwhitebox.com
            # {{- range .Values.traefik.entrypoints }}
            # - --entryPoints.{{ .name }}.address=:{{ .port }}/{{ lower .protocol }}
            # {{- end }}                
            # {{- if .Values.traefik.certificateIssuer.enabled }}
            # - --certificatesresolvers.letsencrypt
            # - --certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
            # #https://acme-v02.api.letsencrypt.org/directory
            # - --certificatesresolvers.letsencrypt.acme.certificatesduration=2160
            # - --certificatesresolvers.letsencrypt.acme.email={{ .Values.traefik.certificateIssuer.solvers.dns.email }}
            # - --certificatesresolvers.letsencrypt.acme.storage=acme.json
            # - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
            # - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53
            # {{- if .Values.traefik.certificateIssuer.solvers.dns.enabled }}
            # - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider={{ .Values.traefik.certificateIssuer.solvers.dns.provider }}
            # {{- end }}
            # {{- end }}
            # {{- end }}

          {{- end }}
          {{- if .Values.service.enabled }}
          ports:
            {{- if .Values.service.loadbalancer }}
            {{- range .Values.service.loadbalancer }}
            - name: {{ .name }}
              containerPort: {{ .port }}
            {{- end }}
            {{- end }}
            {{- if .Values.service.clusterip }}
            {{- range .Values.service.clusterip }}
            - name: {{ .name }}
              containerPort: {{ .port }}
            {{- end }}
            {{- end }}
          {{- end }}
