{{- if .Values.ingress.traefik.enabled }}
{{- range .Values.ingress.traefik.hosts }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}
spec:
  entryPoints:
    - {{ .entrypoint }}
  routes:
  - match: Host(`traefik.projectwhitebox.com`)
    kind: Rule
    services:
    - name: {{ $.Release.Name }}-clusterip
      port: 8080
  tls:
    secretName: wildcard-lachlan-io-tls
{{- end }}
{{- end }}