{{- if .Values.ingress.traefik.enabled }}
{{- range .Values.ingress.traefik.hosts }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}
spec:
  entryPoints:
    - {{ .entrypoint }}
  routes:
  - match: Host(`{{ .host }}`)
    kind: Rule
    services:
    - name: {{ $.Release.Name }}-clusterip
      port: {{ .backendPort }}
{{- if .tls }}
  tls:
    certResolver: myresolver
{{- end }}
{{- end }}
{{- end }}