{{- if .Values.ingress.traefik.enabled }}
{{- range .Values.ingress.traefik.hosts }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "{{ .entrypoint }}"
{{- if .middlewares }}
    traefik.ingress.kubernetes.io/router.middlewares: "{{ join "," .middlewares }}"
{{- end }}
spec:
 tls:
   - hosts:
       - {{ .host }}
     secretName: certificate-secret
  rules:
  - host: {{ .host }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: "{{ $.Release.Name }}-{{ .name }}"
            port:
              number: {{ .backendPort }}
{{- end }}
{{- end }}
