{{- if .Values.ingress.traefik.enabled }}
{{- range .Values.ingress.traefik.hosts }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Release.Name }}
spec:
  entryPoints:
    - {{ .entrypoint }}
  routes:
  - match: Host(`{{ .host }}`)
    kind: Rule
    services:
    - name: {{ $.Release.Name }}-clusterip
      port: {{ .backendPort }}
    middlewares:
      - name: security-headers
      {{- if .Values.ingress.traefik.cors.enabled }}
      - name: {{ $.Release.Name }}-cors
      {{- end}}
{{- if .tls }}
  tls:
    secretName: {{ $.Values.traefik.certificateIssuer.name }}-tls
{{- end }}
{{- end }}
{{- end }}