
{{- if eq .Release.Name "emby" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test
  namespace: platform-domain
spec:
  hosts:
  - emby.projectwhitebox.com
  gateways:
  - platform-ingress/public-ingress-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8096
        host: emby-clusterip.platform-domain.svc.cluster.local
{{- end}}