{{- if .Values.ingress.traefik.cors.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-cors
spec:
  headers:
    accessControlAllowMethods:
      {{- range .Values.ingress.traefik.cors.accessControlAllowMethods }}
      - "{{ . }}"
      {{- end }}
    accessControlAllowHeaders:
      {{- range .Values.ingress.traefik.cors.accessControlAllowHeaders }}
      - "{{ . }}"
      {{- end }}
    accessControlAllowOriginList:
      {{- range .Values.ingress.traefik.cors.accessControlAllowOriginList }}
      - "{{ . }}"
      {{- end }}
    accessControlMaxAge: {{ .Values.ingress.traefik.cors.accessControlMaxAge }}
    addVaryHeader: {{ .Values.ingress.traefik.cors.addVaryHeader }}
{{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
spec:
  headers:
    customResponseHeaders:
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"
      X-Frame-Options: "SAMEORIGIN"
      Content-Security-Policy: "upgrade-insecure-requests"
      Server: "Proxy"
      X-Powered-By: "Proxy"
      Permissions-Policy: "interest-cohort=()"