{{- if and .Values.service.enabled .Values.service.clusterip }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-clusterip
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
  {{- range .Values.service.clusterip }}
  - name: {{ .name }}
    protocol: {{ .protocol }}
    port: {{ .port }}
  {{- end }}
{{- end }}

{{- if and .Values.service.enabled .Values.service.nodeport }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nodeport
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
  {{- range .Values.service.nodeport }}
  - name: {{ .name }}
    protocol: {{ .protocol }}
    port: {{ .port }}
    nodePort: {{ .nodePort }}
  {{- end }}
{{- end }}
