type: statefulset
replicaCount: 3

image:
  registry: "docker.io"
  repository: "postgres"
  tag: "16.2"

containerEnvsConfigMap:
  - name: POSTGRES_DB
    configMap: postgres-secret
  - name: POSTGRES_USER
    configMap: postgres-secret
  - name: POSTGRES_PASSWORD
    configMap: postgres-secret

service:
  enabled: true
  headless: true
  clusterip:
    - name: postgresql
      protocol: TCP
      port: 5432

storage:
  enabled: true
  volumes:
    - name: "config"
      type: "host"
      hostPath: "/mnt/test-pool/data/postgresql"
      mountPath: "/var/lib/postgresql/data"
      readOnly: false