image:
  registry: ""
  repository: ""
  tag: ""

containerArgs: []

resources:
  enabled: false
  requests:
    cpu: 128m
    memory: 128Mi
  limits:
    cpu: 128m
    memory: 128Mi
    gpu: 1

service:
  enabled: false
  clusterip: []
  nodeport: []

serviceAccount:
  enabled: false

rbac:
  enabled: false
  type: role #role or clusterrole
  rules: []
    # - apiGroups: []
    #   resources: []
    #   verbs: []

certificateIssuer:
  enabled: false
  contactEmail: "contact@example.com"
  cloudflareEmail: "hello@example.com"
  dnzZones:
    - "example.com"

ingress:
  traefik:
    enabled: false
    hosts:
    - name: https
      entrypoint: "websecure"
      host: "example.com"
      middlewares:
      - "basic"
      certManager:
        enabled: true
        issuer: "test/example" # namespace/issuerName or just issuerName for cluster issuer
    - name: http
      entrypoint: "web"
      host: "example.com"
      middlewares:
      - "basic"
      - "http"
      certManager:
        enabled: false
        issuer: "" # namespace/issuerName or just issuerName for cluster issuer

# storage:
#   enabled: false
#   - name: "config"
#     type: "pvc"
#     size: "256Gi"
#     mountPath: "/config"
#     readOnly: false
#   - name: "test"
#     type: "host"
#     hostPath: "/etc/config"
#     mountPath: "/test"
#     readOnly: true
#   - name: "test"
#     type: "emptyDir"
#     size: "1G"
#     mountPath: "/config"
#     readOnly: false
