image:
  registry: ""
  repository: ""
  tag: ""

containerArgs: []
containerEnvs: []

probes:
  readiness:
    enabled: false
    type: "http"
    httpPath: "/healthz"
    httpPort: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  liveness:
    enabled: false
    type: "tcp"
    tcpPort: 8080
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  startup:
    enabled: false
    type: "exec"
    execCommand: "some-command"
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 3

resources:
  enabled: false
  requests:
    cpu: 128m
    memory: 128Mi
  limits:
    cpu: 128m
    memory: 128Mi
    gpu: 1

service:
  enabled: false
  clusterip: []
  loadbalancer: []

serviceAccount:
  enabled: true

rbac:
  enabled: false
  type: role
  rules: []

ingress:
  traefik:
    enabled: false
    hosts:
    - name: https
      entrypoint: "websecure"
      host: "example.com"
      middlewares:
      - "basic"
      certManager:
        enabled: true
        issuer: "test/example" # namespace/issuerName or just issuerName for cluster issuer
    - name: http
      entrypoint: "web"
      host: "example.com"
      middlewares:
      - "basic"
      - "http"
      certManager:
        enabled: false
        issuer: "" # namespace/issuerName or just issuerName for cluster issuer

storage:
  enabled: false
  volumes: []