kyverno:
  crds:
    install: true
  config:
    excludeKyvernoNamespace: false
  admissionController:
    replicas: 3
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
      minAvailable: []
  backgroundController:
    replicas: 3
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
      minAvailable: []
  cleanupController:
    replicas: 3
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
      minAvailable: []
  reportsController:
    replicas: 3
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
      minAvailable: []