type: deployment
replicaCount: 1
terminationGracePeriodSeconds: 10

securityContext:
  user: 556   

containerEnvs:
  - name: RADARR__POSTGRES_USER
    value: "radarr"
  - name: RADARR__POSTGRES_HOST
    value: "radarr-rw.platform-data.svc.cluster.local"
  - name: RADARR__POSTGRES_PORT
    value: "5432"
  - name: POSTGRES_USER
    value: "radarr"
  - name: RADARR__POSTGRES_MAIN_DB
    value: "radarr"
  - name: RADARR__POSTGRES_LOG_DB
    value: "radarr"
  - name: "RADARR__LOG_LEVEL"
    value: "info"
  - name: RADARR__INSTANCE_NAME
    value: "Radarr"
  - name: RADARR__AUTHENTICATION_METHOD
    value: "None"

database:
  postgresql:
    enabled: true
    databases: ["radarr-main", "radarr-log"]

containerEnvsSecret:
  - name: RADARR__POSTGRES_PASSWORD
    key: password
    secret: radarr-database-credentials
  # - name: RADARR__API_KEY
  #   key: API_KEY
  #   secret: radarr-api-credentials

image:
  registry: "ghcr.io"
  repository: "onedr0p/radarr"
  tag: "5.3.6.8612@sha256:e9586ce6fdcb0bc739f96490e876c445114cec98e8c039aab6e48c579590cc70"

service:
  enabled: true
  headless: false
  publishNotReadyAddresses: true
  loadbalancer:
    - name: radarr
      protocol: TCP
      port: 7878

storage:
  enabled: true
  volumes:
    - name: "config"
      type: "pvc"
      mountPath: "/config"
      accessModes:
      - ReadWriteOnce
      # - ReadWriteMany # Can't use with local-path
      storageClass: "local-path"
      size: 1Gi
      readOnly: false