type: deployment
replicaCount: 1

podDisruptionBudget: 0
terminationGracePeriodSeconds: 10

securityContext:
  user: 556   

containerEnvs:
  - name: POSTGRES_DB
    value: "radarr"
  - name: POSTGRES_USER
    value: "radarr"

containerEnvsSecret:
  - name: POSTGRES_PASSWORD
    key: DATABASE_PASSWORD
    secret: radarr-database-credentials

image:
  registry: "ghcr.io"
  repository: "onedr0p/radarr"
  tag: "5.3.6.8612@sha256:e9586ce6fdcb0bc739f96490e876c445114cec98e8c039aab6e48c579590cc70"

service:
  enabled: true
  headless: false
  publishNotReadyAddresses: true
  loadbalancer:
    - name: radarr
      protocol: TCP
      port: 7878

storage:
  enabled: true
  volumes:
    - name: "config"
      type: "pvc"
      mountPath: "/config"
      accessModes:
      - ReadWriteMany
      storageClass: "local-path"
      readOnly: false