type: deploymen
replicaCount: 1

podDisruptionBudget: 0
terminationGracePeriodSeconds: 10

securityContext:
  user: 556   

containerEnvs:
  - name: POSTGRES_DB
    value: "radarr"
  - name: POSTGRES_USER
    value: "radarr"

containerEnvsSecret:
  - name: POSTGRES_PASSWORD
    key: DATABASE_PASSWORD
    secret: radarr-database-credentials

image:
  registry: "docker.io"
  repository: "linuxserver/radarr"
  tag: "5.3.6"

service:
  enabled: true
  headless: true
  publishNotReadyAddresses: true
  loadbalancer:
    - name: radarr
      protocol: TCP
      port: 7878

storage:
  enabled: true
  volumes:
    - name: "config"
      type: "host"
      hostPath: "/mnt/test-pool/config/radarr"
      mountPath: "/config"
      readOnly: false