type: deployment
replicaCount: 1

image:
  registry: "docker.io"
  repository: "jellyfin/jellyfin"
  tag: "10.8.13"

probes:
  readiness:
    enabled: true
    type: "http"
    httpPath: "/health"
    httpPort: 8096
    initialDelaySeconds: 2
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 1
  liveness:
    enabled: true
    type: "http"
    httpPath: "/health"
    httpPort: 8096
    initialDelaySeconds: 2
    periodSeconds: 10
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3
  startup:
    enabled: true
    type: "http"
    httpPath: "/health"
    httpPort: 8096
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3

database:
  postgresql:
    enabled: false

service:
  enabled: true
  loadbalancer:
    - name: jellyfin
      protocol: TCP
      port: 8096

storage:
  enabled: true
  volumes:
    - name: "config"
      type: "host"
      hostPath: "/mnt/test-pool/config/jellyfin"
      mountPath: "/config"
      readOnly: false